### PR TITLE
index.html: make content editable

### PR DESCRIPTION
**Pull request by machinekoder**
This patch allows Browser plugins for grammar and spell-checking to work with livedown. The idea is to make the whole web page editable so spell-checker recognize it as input.

EDIT: tested with Grammarly for Chrome

### CODE REVIEW

**Comment by shime** [comment]
Danke Alexander!

**Comment by shime** [comment]
It would also be cool if the original file was updated as we update the content in the browser.

**Comment by machinekoder** [comment]
Indeed!

**Comment by shime** [comment]
Reverted your commit, sorry. It makes links unclickable when previewing.

**Pull request merged**
