### PR TITLE
change markdown parser to showdown, enable gfm checklists

### PR DESCRIPTION
**Pull request by alan7yg**
- [ ] tasklists enabled by replacing markdown parser with [showdown](https://github.com/showdownjs/showdown)

### CODE REVIEW

**Comment by shime** [comment]
How is this better?

**Comment by niftylettuce** [comment]
I really like `markdown-it`, `markdown-it-footnote`, and `markdown-it-checkbox` for checkbox support.

**Comment by niftylettuce** [comment]
@shime @alan7yg please see my pull request here <https://github.com/shime/livedown/pull/27>.

It uses `markdown-it` with support for emojis, checkboxes, and permalinks (just like GitHub).  It also has a cleaner API and is better suited for this.

At first I tried using <https://github.com/ianks/octodown> since it has support for emojis, but then I realized that it's not a real-time update (there's a 500ms+ delay before updates render in the browser, and also vim support for itwasn't as easy to set up) -- therefore I forked this repo and submitted the PR.

Please accept and release a new version!

**Comment by niftylettuce** [comment]
See version 2.0.0 with support for GFM checkboxes, emojis, permalinks, and more!

<https://github.com/shime/livedown/pull/27#issuecomment-320188088>

**Pull request closed without merging**
